# 应用名称
spring:
  application:
    name: intervention-service
server:
  port: 9021

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/
